spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_mybatis?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: huidong
    password: huidong
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true